{
 "title": "CPU usage per container",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Network received per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_io_kubernetes_pod_namespace=\"k3s-deployment\", container_label_io_kubernetes_container_name!=\"\"}[1m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"k3s-deployment\", container_label_io_kubernetes_container_name!=\"\"}[1m]) * 100",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmitted per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_io_kubernetes_pod_namespace=\"k3s-deployment\", container_label_io_kubernetes_container_name!=\"\"}[1m])",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_io_kubernetes_pod_namespace=\"k3s-deployment\", container_label_io_kubernetes_container_name!=\"\"}",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "Overall host RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}