apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: k3s-deployment
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
    password_file /mosquitto/config/pwfile
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout
  pwfile: |
    espuser:$7$101$6rXjoCvuAABZL+PA$6KVub9fqkbyZp8zECOM6Ya4OSFRaDE389of0b/z+rVfT1JVRo88ht5poC89UhpO17Ef8/MWfXgR1a6QrChCeMw==
