apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: k3s-deployment
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    persistence true
    persistence_location /mosquitto/data/
    password_file /mosquitto/config/pwfile
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout
  pwfile: |
    espuser:$7$101$BH3vXTunR8US51Qd$zwvnrRp9BBhychbBr7alHyci/wszzWzuaKeQizv/eMH/3+TzVz8ezdRgYqiop+7yeVOUc/m+1z9loz6zn++uog==
